---
url: "http://ergast.com/downloads/f1db_csv.zip"
assets:
  - file: circuits.csv
    asset_name: circuits
  - file: constructor_results.csv
    asset_name: constructor_results
  - file: constructor_standings.csv
    asset_name: constructor_standings
  - file: constructors.csv
    asset_name: constructors
  - file: driver_standings.csv
    asset_name: driver_standings
  - file: drivers.csv
    asset_name: drivers
  - file: lap_times.csv
    asset_name: lap_times
  - file: pit_stops.csv
    asset_name: pit_stops
  - file: qualifying.csv
    asset_name: qualifying
  - file: races.csv
    asset_name: races
  - file: results.csv
    asset_name: results
  - file: seasons.csv
    asset_name: seasons
  - file: sprint_results.csv
    asset_name: sprint_results
  - file: status.csv
    asset_name: status
